baseurl: "http://lidavidm.github.io"
markdown: maruku
include: ["sympy/_static", "sympy/_images", "sympy/_modules"]

patent_articles:
  - title: "Wi-Fi patent troll hit with racketeering suit emerges unscathed"
    url: "http://arstechnica.com/tech-policy/2013/02/wi-fi-patent-troll-hit-with-novel-anti-racketeering-charges-emerges-unscathed/"
    summary: "Setting up a Wi-Fi network? One patent troll would try to sue you"

  - title: "Software patent reform just died in the House, thanks to IBM and Microsoft"
    url: "http://www.washingtonpost.com/blogs/the-switch/wp/2013/11/20/software-patent-reform-just-died-in-the-house-thanks-to-ibm-and-microsoft/"
    summary: "Industry lobbying hampers Congressional efforts to curb software patent abuse"

  - title: "A look at the patent on distributing podcasts, and EFF's plan to fight it"
    url: "http://www.theverge.com/2013/5/31/4381486/A-podcast-distribution-patent-EFF-wants-help-invalidating"
    summary: "Like listening to podcasts? One patent troll claims it owns the idea of distributing them"

  - title: "Google and Samsung sued for patent infringement by major tech consortium"
    url: "http://www.theverge.com/2013/10/31/5052962/google-and-samsung-sued-for-patent-infringement-by-major-tech-consortium-rockstar"
    summary: "A consortium that counts Apple and Microsoft among its members sues Google; its patents are so broad that its CEO says “Pretty much anybody out there is infringing”"

  - title: "Obama administration backs patent troll bill, House vote set for this week"
    url: "http://www.theverge.com/2013/12/3/5172084/white-house-supports-innovation-act-house-patent-troll-reform"
    summary: "President Obama supports the Innovation Act to make it easier for businesses to defend against patent trolls"

  - title: "“Shopping cart” patent troll tries to save itself, gets pounded by Newegg"
    url: "http://arstechnica.com/tech-policy/2013/09/shopping-cart-patent-troll-tries-to-save-itself-gets-pounded-by-newegg/"
    summary: "Newegg stands up to a patent troll that claims it owns the concept of a shopping cart"

  - title: "Ask Patents"
    url: "http://patents.stackexchange.com"
    summary: "StackExchange’s effort to take down patents by crowdsourcing the discovery of relevant prior art"

  - title: "Victory Lap for Ask Patents"
    url: "http://www.joelonsoftware.com/items/2013/07/22.html"
    summary: '<a href="http://patents.stackexchange.com/">Ask Patents</a> successfully provides prior art that causes the US Patent Office to reject an invalid patent'

  - title: "Patent Office asks the public for advice on software patents"
    url: "http://www.theverge.com/2013/1/4/3835118/patent-office-asks-public-advice-on-software-patents"
    summary: 'The US Patent Office <a href="http://www.uspto.gov/patents/init_events/software_partnership.jsp">wants feedback</a> on how to deal with software patents'

  - title: "Talking Software Patents with the Patent Office: A Sign of Reform to Come?"
    url: "https://www.eff.org/deeplinks/2013/02/talking-software-patents-patent-office-sign-reform-come"
    summary: "The Electronic Frontier Foundation’s solution to overly broad patents"

  - title: "New Zealand just abolished software patents. Here’s why we should, too."
    url: "http://www.washingtonpost.com/blogs/the-switch/wp/2013/08/29/new-zealand-just-abolished-software-patents-heres-why-we-should-too/"
    summary: "The Government Accountability Office finds software patents to be a major burden on the patent system"
